// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.
package dllist

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"golang.org/x/text/encoding/unicode"
	"io"
)


type NinchDllist_Genre int
const (
	NinchDllist_Genre__Action       NinchDllist_Genre = 1
	NinchDllist_Genre__Adventure    NinchDllist_Genre = 2
	NinchDllist_Genre__LifeTraining NinchDllist_Genre = 3
	NinchDllist_Genre__Sports       NinchDllist_Genre = 4
	NinchDllist_Genre__Puzzles      NinchDllist_Genre = 5
	NinchDllist_Genre__RolePlaying  NinchDllist_Genre = 6
	NinchDllist_Genre__Racing       NinchDllist_Genre = 7
	NinchDllist_Genre__Strategy     NinchDllist_Genre = 8
	NinchDllist_Genre__Simulation   NinchDllist_Genre = 9
	NinchDllist_Genre__MusicRhythm  NinchDllist_Genre = 10
	NinchDllist_Genre__BoardGame    NinchDllist_Genre = 11
	NinchDllist_Genre__Shooter      NinchDllist_Genre = 12
	NinchDllist_Genre__Other        NinchDllist_Genre = 13
	NinchDllist_Genre__Fighting     NinchDllist_Genre = 14
	NinchDllist_Genre__Arcade       NinchDllist_Genre = 15
	NinchDllist_Genre__Imports      NinchDllist_Genre = 16
)

type NinchDllist_YesNo int
const (
	NinchDllist_YesNo__True  NinchDllist_YesNo = 0
	NinchDllist_YesNo__False NinchDllist_YesNo = 1
)

type NinchDllist_EveryoneGamers int
const (
	NinchDllist_EveryoneGamers__Gamers   NinchDllist_EveryoneGamers = 0
	NinchDllist_EveryoneGamers__Everyone NinchDllist_EveryoneGamers = 1
)

type NinchDllist_Medal int
const (
	NinchDllist_Medal__None     NinchDllist_Medal = 0
	NinchDllist_Medal__Bronze   NinchDllist_Medal = 1
	NinchDllist_Medal__Silver   NinchDllist_Medal = 2
	NinchDllist_Medal__Gold     NinchDllist_Medal = 3
	NinchDllist_Medal__Platinum NinchDllist_Medal = 4
)

type NinchDllist_Platforms int
const (
	NinchDllist_Platforms__None            NinchDllist_Platforms = 0
	NinchDllist_Platforms__Wii             NinchDllist_Platforms = 1
	NinchDllist_Platforms__WiiChannels     NinchDllist_Platforms = 2
	NinchDllist_Platforms__Nes             NinchDllist_Platforms = 3
	NinchDllist_Platforms__Snes            NinchDllist_Platforms = 4
	NinchDllist_Platforms__N64             NinchDllist_Platforms = 5
	NinchDllist_Platforms__Tg16            NinchDllist_Platforms = 6
	NinchDllist_Platforms__Genesis         NinchDllist_Platforms = 7
	NinchDllist_Platforms__Neogeo          NinchDllist_Platforms = 8
	NinchDllist_Platforms__Ds              NinchDllist_Platforms = 10
	NinchDllist_Platforms__Wiiware         NinchDllist_Platforms = 11
	NinchDllist_Platforms__Master          NinchDllist_Platforms = 12
	NinchDllist_Platforms__C64             NinchDllist_Platforms = 13
	NinchDllist_Platforms__Arcade          NinchDllist_Platforms = 14
	NinchDllist_Platforms__Dsi             NinchDllist_Platforms = 16
	NinchDllist_Platforms__Dsiware         NinchDllist_Platforms = 17
	NinchDllist_Platforms__Threeds         NinchDllist_Platforms = 18
	NinchDllist_Platforms__ThreedsDownload NinchDllist_Platforms = 19
	NinchDllist_Platforms__ThreedsGameboy  NinchDllist_Platforms = 20
)

type NinchDllist_RatingGroup int
const (
	NinchDllist_RatingGroup__Cero     NinchDllist_RatingGroup = 1
	NinchDllist_RatingGroup__Esrb     NinchDllist_RatingGroup = 2
	NinchDllist_RatingGroup__Usk      NinchDllist_RatingGroup = 3
	NinchDllist_RatingGroup__Pegi     NinchDllist_RatingGroup = 4
	NinchDllist_RatingGroup__PegiFin  NinchDllist_RatingGroup = 5
	NinchDllist_RatingGroup__PegiPor  NinchDllist_RatingGroup = 6
	NinchDllist_RatingGroup__Bbfc     NinchDllist_RatingGroup = 7
	NinchDllist_RatingGroup__OflcAgcb NinchDllist_RatingGroup = 8
	NinchDllist_RatingGroup__OflcNz   NinchDllist_RatingGroup = 9
)

type NinchDllist_AloneWithFriends int
const (
	NinchDllist_AloneWithFriends__WithFriends NinchDllist_AloneWithFriends = 0
	NinchDllist_AloneWithFriends__Alone       NinchDllist_AloneWithFriends = 1
)

type NinchDllist_CasualHardcore int
const (
	NinchDllist_CasualHardcore__Hardcore NinchDllist_CasualHardcore = 0
	NinchDllist_CasualHardcore__Casual   NinchDllist_CasualHardcore = 1
)

type NinchDllist_VideoType int
const (
	NinchDllist_VideoType__None                  NinchDllist_VideoType = 0
	NinchDllist_VideoType__Wii                   NinchDllist_VideoType = 1
	NinchDllist_VideoType__Wiiware               NinchDllist_VideoType = 2
	NinchDllist_VideoType__WiiVirtualConsole     NinchDllist_VideoType = 3
	NinchDllist_VideoType__Ds                    NinchDllist_VideoType = 4
	NinchDllist_VideoType__Dsi                   NinchDllist_VideoType = 5
	NinchDllist_VideoType__Dsiware               NinchDllist_VideoType = 6
	NinchDllist_VideoType__Message               NinchDllist_VideoType = 7
	NinchDllist_VideoType__Threeds               NinchDllist_VideoType = 8
	NinchDllist_VideoType__ThreedsVirtualConsole NinchDllist_VideoType = 10
)
type NinchDllist struct {
	Unknown uint16
	Version uint8
	UnknownRegion uint8
	Filesize uint32
	Crc32 uint32
	Dllistid uint32
	ThumbnailId uint32
	CountryCode uint32
	LanguageCode uint32
	Unknown2 []uint8
	RatingsEntryNumber uint32
	RatingsTableOffset uint32
	TitleTypesEntryNumber uint32
	TitleTypesTableOffset uint32
	CompanyEntryNumber uint32
	CompanyTableOffset uint32
	TitleEntryNumber uint32
	TitleTableOffset uint32
	NewTitleEntryNumber uint32
	NewTitleTableOffset uint32
	Videos1EntryNumber uint32
	Videos1TableOffset uint32
	NewVideoEntryNumber uint32
	NewVideoTableOffset uint32
	DemosEntryNumber uint32
	DemosTableOffset uint32
	Unknown5 uint32
	Unknown6 uint32
	RecommendationsEntryNumber uint32
	RecommendationsTableOffset uint32
	Unknown7 []uint32
	RecentRecommendationsEntryNumber uint32
	RecentRecommendationsTableOffset uint32
	Unknown8 []uint32
	PopularVideosEntryNumber uint32
	PopularVideosTableOffset uint32
	DetailedRatingsEntryNumber uint32
	DetailedRatingsTableOffset uint32
	LastUpdate string
	Unknown9 []uint8
	DlUrlIds []string
	Unknown10 uint32
	_io *kaitai.Stream
	_root *NinchDllist
	_parent interface{}
	_f_demosTable bool
	demosTable []*NinchDllist_DemosTable
	_f_ratingsTable bool
	ratingsTable []*NinchDllist_RatingsTable
	_f_videos1Table bool
	videos1Table []*NinchDllist_Videos1Table
	_f_recentRecommendationsTable bool
	recentRecommendationsTable []*NinchDllist_RecentRecommendationsTable
	_f_titleTable bool
	titleTable []*NinchDllist_TitleTable
	_f_detailedRatingsTable bool
	detailedRatingsTable []*NinchDllist_DetailedRatingsTable
	_f_popularVideosTable bool
	popularVideosTable []*NinchDllist_PopularVideosTable
	_f_titleTypesTable bool
	titleTypesTable []*NinchDllist_TitleTypesTable
	_f_recommendationsTable bool
	recommendationsTable []*NinchDllist_RecommendationsTable
	_f_newVideoTable bool
	newVideoTable []*NinchDllist_NewVideoTable
	_f_newTitleTable bool
	newTitleTable []*NinchDllist_NewTitleTable
	_f_companyTable bool
	companyTable []*NinchDllist_CompanyTable
}
func NewNinchDllist() *NinchDllist {
	return &NinchDllist{
	}
}

func (this *NinchDllist) Read(io *kaitai.Stream, parent interface{}, root *NinchDllist) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.Unknown = uint16(tmp1)
	tmp2, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Version = tmp2
	tmp3, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.UnknownRegion = tmp3
	tmp4, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Filesize = uint32(tmp4)
	tmp5, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Crc32 = uint32(tmp5)
	tmp6, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Dllistid = uint32(tmp6)
	tmp7, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.ThumbnailId = uint32(tmp7)
	tmp8, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.CountryCode = uint32(tmp8)
	tmp9, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.LanguageCode = uint32(tmp9)
	for i := 0; i < int(9); i++ {
		_ = i
		tmp10, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Unknown2 = append(this.Unknown2, tmp10)
	}
	tmp11, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.RatingsEntryNumber = uint32(tmp11)
	tmp12, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.RatingsTableOffset = uint32(tmp12)
	tmp13, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.TitleTypesEntryNumber = uint32(tmp13)
	tmp14, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.TitleTypesTableOffset = uint32(tmp14)
	tmp15, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.CompanyEntryNumber = uint32(tmp15)
	tmp16, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.CompanyTableOffset = uint32(tmp16)
	tmp17, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.TitleEntryNumber = uint32(tmp17)
	tmp18, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.TitleTableOffset = uint32(tmp18)
	tmp19, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.NewTitleEntryNumber = uint32(tmp19)
	tmp20, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.NewTitleTableOffset = uint32(tmp20)
	tmp21, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Videos1EntryNumber = uint32(tmp21)
	tmp22, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Videos1TableOffset = uint32(tmp22)
	tmp23, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.NewVideoEntryNumber = uint32(tmp23)
	tmp24, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.NewVideoTableOffset = uint32(tmp24)
	tmp25, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DemosEntryNumber = uint32(tmp25)
	tmp26, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DemosTableOffset = uint32(tmp26)
	tmp27, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Unknown5 = uint32(tmp27)
	tmp28, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Unknown6 = uint32(tmp28)
	tmp29, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.RecommendationsEntryNumber = uint32(tmp29)
	tmp30, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.RecommendationsTableOffset = uint32(tmp30)
	for i := 0; i < int(4); i++ {
		_ = i
		tmp31, err := this._io.ReadU4be()
		if err != nil {
			return err
		}
		this.Unknown7 = append(this.Unknown7, tmp31)
	}
	tmp32, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.RecentRecommendationsEntryNumber = uint32(tmp32)
	tmp33, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.RecentRecommendationsTableOffset = uint32(tmp33)
	for i := 0; i < int(2); i++ {
		_ = i
		tmp34, err := this._io.ReadU4be()
		if err != nil {
			return err
		}
		this.Unknown8 = append(this.Unknown8, tmp34)
	}
	tmp35, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.PopularVideosEntryNumber = uint32(tmp35)
	tmp36, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.PopularVideosTableOffset = uint32(tmp36)
	tmp37, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DetailedRatingsEntryNumber = uint32(tmp37)
	tmp38, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.DetailedRatingsTableOffset = uint32(tmp38)
	tmp39, err := this._io.ReadBytes(int(62))
	if err != nil {
		return err
	}
	tmp39 = tmp39
	tmp40, err := kaitai.BytesToStr(tmp39, unicode.UTF16(unicode.BigEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.LastUpdate = tmp40
	for i := 0; i < int(3); i++ {
		_ = i
		tmp41, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Unknown9 = append(this.Unknown9, tmp41)
	}
	for i := 0; i < int(5); i++ {
		_ = i
		tmp42, err := this._io.ReadBytes(int(256))
		if err != nil {
			return err
		}
		tmp42 = tmp42
		this.DlUrlIds = append(this.DlUrlIds, string(tmp42))
	}
	tmp43, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Unknown10 = uint32(tmp43)
	return err
}
func (this *NinchDllist) DemosTable() (v []*NinchDllist_DemosTable, err error) {
	if (this._f_demosTable) {
		return this.demosTable, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.DemosTableOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.DemosEntryNumber); i++ {
		_ = i
		tmp44 := NewNinchDllist_DemosTable()
		err = tmp44.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.demosTable = append(this.demosTable, tmp44)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_demosTable = true
	this._f_demosTable = true
	return this.demosTable, nil
}
func (this *NinchDllist) RatingsTable() (v []*NinchDllist_RatingsTable, err error) {
	if (this._f_ratingsTable) {
		return this.ratingsTable, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.RatingsTableOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.RatingsEntryNumber); i++ {
		_ = i
		tmp45 := NewNinchDllist_RatingsTable()
		err = tmp45.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.ratingsTable = append(this.ratingsTable, tmp45)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_ratingsTable = true
	this._f_ratingsTable = true
	return this.ratingsTable, nil
}
func (this *NinchDllist) Videos1Table() (v []*NinchDllist_Videos1Table, err error) {
	if (this._f_videos1Table) {
		return this.videos1Table, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Videos1TableOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.Videos1EntryNumber); i++ {
		_ = i
		tmp46 := NewNinchDllist_Videos1Table()
		err = tmp46.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.videos1Table = append(this.videos1Table, tmp46)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_videos1Table = true
	this._f_videos1Table = true
	return this.videos1Table, nil
}
func (this *NinchDllist) RecentRecommendationsTable() (v []*NinchDllist_RecentRecommendationsTable, err error) {
	if (this._f_recentRecommendationsTable) {
		return this.recentRecommendationsTable, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.RecentRecommendationsTableOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.RecentRecommendationsEntryNumber); i++ {
		_ = i
		tmp47 := NewNinchDllist_RecentRecommendationsTable()
		err = tmp47.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.recentRecommendationsTable = append(this.recentRecommendationsTable, tmp47)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_recentRecommendationsTable = true
	this._f_recentRecommendationsTable = true
	return this.recentRecommendationsTable, nil
}
func (this *NinchDllist) TitleTable() (v []*NinchDllist_TitleTable, err error) {
	if (this._f_titleTable) {
		return this.titleTable, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.TitleTableOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.TitleEntryNumber); i++ {
		_ = i
		tmp48 := NewNinchDllist_TitleTable()
		err = tmp48.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.titleTable = append(this.titleTable, tmp48)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_titleTable = true
	this._f_titleTable = true
	return this.titleTable, nil
}
func (this *NinchDllist) DetailedRatingsTable() (v []*NinchDllist_DetailedRatingsTable, err error) {
	if (this._f_detailedRatingsTable) {
		return this.detailedRatingsTable, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.DetailedRatingsTableOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.DetailedRatingsEntryNumber); i++ {
		_ = i
		tmp49 := NewNinchDllist_DetailedRatingsTable()
		err = tmp49.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.detailedRatingsTable = append(this.detailedRatingsTable, tmp49)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_detailedRatingsTable = true
	this._f_detailedRatingsTable = true
	return this.detailedRatingsTable, nil
}
func (this *NinchDllist) PopularVideosTable() (v []*NinchDllist_PopularVideosTable, err error) {
	if (this._f_popularVideosTable) {
		return this.popularVideosTable, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.PopularVideosTableOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.PopularVideosEntryNumber); i++ {
		_ = i
		tmp50 := NewNinchDllist_PopularVideosTable()
		err = tmp50.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.popularVideosTable = append(this.popularVideosTable, tmp50)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_popularVideosTable = true
	this._f_popularVideosTable = true
	return this.popularVideosTable, nil
}
func (this *NinchDllist) TitleTypesTable() (v []*NinchDllist_TitleTypesTable, err error) {
	if (this._f_titleTypesTable) {
		return this.titleTypesTable, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.TitleTypesTableOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.TitleTypesEntryNumber); i++ {
		_ = i
		tmp51 := NewNinchDllist_TitleTypesTable()
		err = tmp51.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.titleTypesTable = append(this.titleTypesTable, tmp51)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_titleTypesTable = true
	this._f_titleTypesTable = true
	return this.titleTypesTable, nil
}
func (this *NinchDllist) RecommendationsTable() (v []*NinchDllist_RecommendationsTable, err error) {
	if (this._f_recommendationsTable) {
		return this.recommendationsTable, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.RecommendationsTableOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.RecommendationsEntryNumber); i++ {
		_ = i
		tmp52 := NewNinchDllist_RecommendationsTable()
		err = tmp52.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.recommendationsTable = append(this.recommendationsTable, tmp52)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_recommendationsTable = true
	this._f_recommendationsTable = true
	return this.recommendationsTable, nil
}
func (this *NinchDllist) NewVideoTable() (v []*NinchDllist_NewVideoTable, err error) {
	if (this._f_newVideoTable) {
		return this.newVideoTable, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.NewVideoTableOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NewVideoEntryNumber); i++ {
		_ = i
		tmp53 := NewNinchDllist_NewVideoTable()
		err = tmp53.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.newVideoTable = append(this.newVideoTable, tmp53)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_newVideoTable = true
	this._f_newVideoTable = true
	return this.newVideoTable, nil
}
func (this *NinchDllist) NewTitleTable() (v []*NinchDllist_NewTitleTable, err error) {
	if (this._f_newTitleTable) {
		return this.newTitleTable, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.NewTitleTableOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.NewTitleEntryNumber); i++ {
		_ = i
		tmp54 := NewNinchDllist_NewTitleTable()
		err = tmp54.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.newTitleTable = append(this.newTitleTable, tmp54)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_newTitleTable = true
	this._f_newTitleTable = true
	return this.newTitleTable, nil
}
func (this *NinchDllist) CompanyTable() (v []*NinchDllist_CompanyTable, err error) {
	if (this._f_companyTable) {
		return this.companyTable, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.CompanyTableOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.CompanyEntryNumber); i++ {
		_ = i
		tmp55 := NewNinchDllist_CompanyTable()
		err = tmp55.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.companyTable = append(this.companyTable, tmp55)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_companyTable = true
	this._f_companyTable = true
	return this.companyTable, nil
}

/**
 * 0 for v3, 0x39 for v4 JP
 */

/**
 * Part of the path in the URL for the Nintendo Channel files.
 */
type NinchDllist_NewVideoTable struct {
	Id uint32
	Unknown uint16
	TitleId uint32
	Unknown2 []uint8
	Title string
	_io *kaitai.Stream
	_root *NinchDllist
	_parent *NinchDllist
}
func NewNinchDllist_NewVideoTable() *NinchDllist_NewVideoTable {
	return &NinchDllist_NewVideoTable{
	}
}

func (this *NinchDllist_NewVideoTable) Read(io *kaitai.Stream, parent *NinchDllist, root *NinchDllist) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp56, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Id = uint32(tmp56)
	tmp57, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.Unknown = uint16(tmp57)
	tmp58, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.TitleId = uint32(tmp58)
	for i := 0; i < int(18); i++ {
		_ = i
		tmp59, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Unknown2 = append(this.Unknown2, tmp59)
	}
	tmp60, err := this._io.ReadBytes(int(204))
	if err != nil {
		return err
	}
	tmp60 = tmp60
	tmp61, err := kaitai.BytesToStr(tmp60, unicode.UTF16(unicode.BigEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.Title = tmp61
	return err
}

/**
 * Decimal ID for URL filename.
 */

/**
 * Time length?
 */
type NinchDllist_RecommendationsTable struct {
	RecommendationTitleOffset uint32
	_io *kaitai.Stream
	_root *NinchDllist
	_parent *NinchDllist
	_f_recommendationTitleEntry bool
	recommendationTitleEntry *NinchDllist_TitleTable
}
func NewNinchDllist_RecommendationsTable() *NinchDllist_RecommendationsTable {
	return &NinchDllist_RecommendationsTable{
	}
}

func (this *NinchDllist_RecommendationsTable) Read(io *kaitai.Stream, parent *NinchDllist, root *NinchDllist) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp62, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.RecommendationTitleOffset = uint32(tmp62)
	return err
}
func (this *NinchDllist_RecommendationsTable) RecommendationTitleEntry() (v *NinchDllist_TitleTable, err error) {
	if (this._f_recommendationTitleEntry) {
		return this.recommendationTitleEntry, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.RecommendationTitleOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp63 := NewNinchDllist_TitleTable()
	err = tmp63.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.recommendationTitleEntry = tmp63
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_recommendationTitleEntry = true
	this._f_recommendationTitleEntry = true
	return this.recommendationTitleEntry, nil
}
type NinchDllist_NewTitleTable struct {
	NewTitleOffset uint32
	_io *kaitai.Stream
	_root *NinchDllist
	_parent *NinchDllist
	_f_newTitleEntry bool
	newTitleEntry *NinchDllist_TitleTable
}
func NewNinchDllist_NewTitleTable() *NinchDllist_NewTitleTable {
	return &NinchDllist_NewTitleTable{
	}
}

func (this *NinchDllist_NewTitleTable) Read(io *kaitai.Stream, parent *NinchDllist, root *NinchDllist) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp64, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.NewTitleOffset = uint32(tmp64)
	return err
}
func (this *NinchDllist_NewTitleTable) NewTitleEntry() (v *NinchDllist_TitleTable, err error) {
	if (this._f_newTitleEntry) {
		return this.newTitleEntry, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.NewTitleOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp65 := NewNinchDllist_TitleTable()
	err = tmp65.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.newTitleEntry = tmp65
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_newTitleEntry = true
	this._f_newTitleEntry = true
	return this.newTitleEntry, nil
}
type NinchDllist_DetailedRatingsTable struct {
	RatingGroup uint8
	RatingId uint8
	Title string
	_io *kaitai.Stream
	_root *NinchDllist
	_parent *NinchDllist
}
func NewNinchDllist_DetailedRatingsTable() *NinchDllist_DetailedRatingsTable {
	return &NinchDllist_DetailedRatingsTable{
	}
}

func (this *NinchDllist_DetailedRatingsTable) Read(io *kaitai.Stream, parent *NinchDllist, root *NinchDllist) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp66, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.RatingGroup = tmp66
	tmp67, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.RatingId = tmp67
	tmp68, err := this._io.ReadBytes(int(204))
	if err != nil {
		return err
	}
	tmp68 = tmp68
	tmp69, err := kaitai.BytesToStr(tmp68, unicode.UTF16(unicode.BigEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.Title = tmp69
	return err
}
type NinchDllist_CompanyTable struct {
	Id uint32
	DevTitle string
	PubTitle string
	_io *kaitai.Stream
	_root *NinchDllist
	_parent interface{}
}
func NewNinchDllist_CompanyTable() *NinchDllist_CompanyTable {
	return &NinchDllist_CompanyTable{
	}
}

func (this *NinchDllist_CompanyTable) Read(io *kaitai.Stream, parent interface{}, root *NinchDllist) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp70, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Id = uint32(tmp70)
	tmp71, err := this._io.ReadBytes(int(62))
	if err != nil {
		return err
	}
	tmp71 = tmp71
	tmp72, err := kaitai.BytesToStr(tmp71, unicode.UTF16(unicode.BigEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.DevTitle = tmp72
	tmp73, err := this._io.ReadBytes(int(62))
	if err != nil {
		return err
	}
	tmp73 = tmp73
	tmp74, err := kaitai.BytesToStr(tmp73, unicode.UTF16(unicode.BigEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.PubTitle = tmp74
	return err
}
type NinchDllist_PopularVideosTable struct {
	Id uint32
	TimeLength uint16
	TitleId uint32
	BarColor uint8
	Unknown2 []uint8
	RatingId uint8
	Unknown3 uint8
	VideoRank uint8
	Unknown4 uint8
	Title string
	_io *kaitai.Stream
	_root *NinchDllist
	_parent *NinchDllist
}
func NewNinchDllist_PopularVideosTable() *NinchDllist_PopularVideosTable {
	return &NinchDllist_PopularVideosTable{
	}
}

func (this *NinchDllist_PopularVideosTable) Read(io *kaitai.Stream, parent *NinchDllist, root *NinchDllist) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp75, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Id = uint32(tmp75)
	tmp76, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.TimeLength = uint16(tmp76)
	tmp77, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.TitleId = uint32(tmp77)
	tmp78, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.BarColor = tmp78
	for i := 0; i < int(15); i++ {
		_ = i
		tmp79, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Unknown2 = append(this.Unknown2, tmp79)
	}
	tmp80, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.RatingId = tmp80
	tmp81, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Unknown3 = tmp81
	tmp82, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.VideoRank = tmp82
	tmp83, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Unknown4 = tmp83
	tmp84, err := this._io.ReadBytes(int(204))
	if err != nil {
		return err
	}
	tmp84 = tmp84
	tmp85, err := kaitai.BytesToStr(tmp84, unicode.UTF16(unicode.BigEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.Title = tmp85
	return err
}

/**
 * Decimal ID for URL filename.
 */

/**
 * 0 for grey, 1 for blue, 8 for red
 */
type NinchDllist_RecentRecommendationsTable struct {
	RecentRecommendationTitleOffset uint32
	Unknown uint16
	_io *kaitai.Stream
	_root *NinchDllist
	_parent *NinchDllist
	_f_recentRecommendationTitleEntry bool
	recentRecommendationTitleEntry *NinchDllist_TitleTable
}
func NewNinchDllist_RecentRecommendationsTable() *NinchDllist_RecentRecommendationsTable {
	return &NinchDllist_RecentRecommendationsTable{
	}
}

func (this *NinchDllist_RecentRecommendationsTable) Read(io *kaitai.Stream, parent *NinchDllist, root *NinchDllist) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp86, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.RecentRecommendationTitleOffset = uint32(tmp86)
	tmp87, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.Unknown = uint16(tmp87)
	return err
}
func (this *NinchDllist_RecentRecommendationsTable) RecentRecommendationTitleEntry() (v *NinchDllist_TitleTable, err error) {
	if (this._f_recentRecommendationTitleEntry) {
		return this.recentRecommendationTitleEntry, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.RecentRecommendationTitleOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp88 := NewNinchDllist_TitleTable()
	err = tmp88.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.recentRecommendationTitleEntry = tmp88
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_recentRecommendationTitleEntry = true
	this._f_recentRecommendationTitleEntry = true
	return this.recentRecommendationTitleEntry, nil
}
type NinchDllist_TitleTypesTable struct {
	TypeId uint8
	ConsoleModel string
	Title string
	GroupId uint8
	Unknown uint8
	_io *kaitai.Stream
	_root *NinchDllist
	_parent *NinchDllist
}
func NewNinchDllist_TitleTypesTable() *NinchDllist_TitleTypesTable {
	return &NinchDllist_TitleTypesTable{
	}
}

func (this *NinchDllist_TitleTypesTable) Read(io *kaitai.Stream, parent *NinchDllist, root *NinchDllist) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp89, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.TypeId = tmp89
	tmp90, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp90 = tmp90
	this.ConsoleModel = string(tmp90)
	tmp91, err := this._io.ReadBytes(int(102))
	if err != nil {
		return err
	}
	tmp91 = tmp91
	tmp92, err := kaitai.BytesToStr(tmp91, unicode.UTF16(unicode.BigEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.Title = tmp92
	tmp93, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.GroupId = tmp93
	tmp94, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Unknown = tmp94
	return err
}

/**
 * Console model code.
 */

/**
 * Usually matches the last byte of the rating list header.
 */
type NinchDllist_RatingsTable struct {
	RatingId    uint8
	RatingGroup NinchDllist_RatingGroup
	Age         uint8
	Unknown uint8
	JpegOffset uint32
	JpegSize uint32
	Title string
	_io         *kaitai.Stream
	_root       *NinchDllist
	_parent     *NinchDllist
}
func NewNinchDllist_RatingsTable() *NinchDllist_RatingsTable {
	return &NinchDllist_RatingsTable{
	}
}

func (this *NinchDllist_RatingsTable) Read(io *kaitai.Stream, parent *NinchDllist, root *NinchDllist) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp95, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.RatingId = tmp95
	tmp96, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.RatingGroup = NinchDllist_RatingGroup(tmp96)
	tmp97, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Age = tmp97
	tmp98, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Unknown = tmp98
	tmp99, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.JpegOffset = uint32(tmp99)
	tmp100, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.JpegSize = uint32(tmp100)
	tmp101, err := this._io.ReadBytes(int(22))
	if err != nil {
		return err
	}
	tmp101 = tmp101
	tmp102, err := kaitai.BytesToStr(tmp101, unicode.UTF16(unicode.BigEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.Title = tmp102
	return err
}

/**
 * Required years of age.
 */

/**
 * Offset for a picture of this rating.
 */
type NinchDllist_Videos1Table struct {
	Id uint32
	TimeLength uint16
	TitleId   uint32
	VideoType NinchDllist_VideoType
	Unknown   []uint8
	Unknown2 uint8
	RatingId uint8
	Unknown3 uint8
	NewTag uint8
	VideoIndex uint8
	Unknown4 []uint8
	Title string
	_io       *kaitai.Stream
	_root     *NinchDllist
	_parent   *NinchDllist
}
func NewNinchDllist_Videos1Table() *NinchDllist_Videos1Table {
	return &NinchDllist_Videos1Table{
	}
}

func (this *NinchDllist_Videos1Table) Read(io *kaitai.Stream, parent *NinchDllist, root *NinchDllist) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp103, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Id = uint32(tmp103)
	tmp104, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.TimeLength = uint16(tmp104)
	tmp105, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.TitleId = uint32(tmp105)
	tmp106, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.VideoType = NinchDllist_VideoType(tmp106)
	for i := 0; i < int(14); i++ {
		_ = i
		tmp107, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Unknown = append(this.Unknown, tmp107)
	}
	tmp108, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Unknown2 = tmp108
	tmp109, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.RatingId = tmp109
	tmp110, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Unknown3 = tmp110
	tmp111, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NewTag = tmp111
	tmp112, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.VideoIndex = tmp112
	for i := 0; i < int(2); i++ {
		_ = i
		tmp113, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Unknown4 = append(this.Unknown4, tmp113)
	}
	tmp114, err := this._io.ReadBytes(int(246))
	if err != nil {
		return err
	}
	tmp114 = tmp114
	tmp115, err := kaitai.BytesToStr(tmp114, unicode.UTF16(unicode.BigEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.Title = tmp115
	return err
}

/**
 * Decimal ID for URL filename.
 */

/**
 * Length of video measured in seconds.
 */

/**
 * The associated title entry's ID.
 */
type NinchDllist_TitleTable struct {
	Id uint32
	TitleId                           string
	TitleType                         NinchDllist_Platforms
	Genre                             []NinchDllist_Genre
	CompanyOffset                     uint32
	ReleaseDateYear uint16
	ReleaseDateMonth uint8
	ReleaseDateDay uint8
	RatingId uint8
	Unknown1 []uint8
	Unknown2                          bool
	CasualHardcore1                   NinchDllist_CasualHardcore
	Unknown3                          bool
	CasualHardcore2                   NinchDllist_CasualHardcore
	Unknown4                          bool
	CasualHardcore3                   NinchDllist_CasualHardcore
	Unknown5                          bool
	CasualHardcore4                   NinchDllist_CasualHardcore
	Unknown6                          bool
	CasualHardcore5                   NinchDllist_CasualHardcore
	Unknown7                          bool
	CasualHardcore6                   NinchDllist_CasualHardcore
	Unknown8                          bool
	CasualHardcore7                   NinchDllist_CasualHardcore
	Unknown9                          bool
	CasualHardcore8                   NinchDllist_CasualHardcore
	Unknown10                         bool
	CasualHardcore9                   NinchDllist_CasualHardcore
	Unknown11                         bool
	CasualHardcore10                  NinchDllist_CasualHardcore
	Unknown12                         bool
	CasualHardcore11                  NinchDllist_CasualHardcore
	Unknown13                         bool
	CasualHardcore12                  NinchDllist_CasualHardcore
	Unknown14                         uint64
	CasualHardcoreAllAgesAndGenders   NinchDllist_CasualHardcore
	EveryoneGamers1                   NinchDllist_EveryoneGamers
	AloneWithFriends1                 NinchDllist_AloneWithFriends
	EveryoneGamers2                   NinchDllist_EveryoneGamers
	AloneWithFriends2                 NinchDllist_AloneWithFriends
	EveryoneGamers3                   NinchDllist_EveryoneGamers
	AloneWithFriends3                 NinchDllist_AloneWithFriends
	EveryoneGamers4                   NinchDllist_EveryoneGamers
	AloneWithFriends4                 NinchDllist_AloneWithFriends
	EveryoneGamers5                   NinchDllist_EveryoneGamers
	AloneWithFriends5                 NinchDllist_AloneWithFriends
	EveryoneGamers6                   NinchDllist_EveryoneGamers
	AloneWithFriends6                 NinchDllist_AloneWithFriends
	EveryoneGamers7                   NinchDllist_EveryoneGamers
	AloneWithFriends7                 NinchDllist_AloneWithFriends
	EveryoneGamers8                   NinchDllist_EveryoneGamers
	AloneWithFriends8                 NinchDllist_AloneWithFriends
	EveryoneGamers9                   NinchDllist_EveryoneGamers
	AloneWithFriends9                 NinchDllist_AloneWithFriends
	EveryoneGamers10                  NinchDllist_EveryoneGamers
	AloneWithFriends10                NinchDllist_AloneWithFriends
	EveryoneGamers11                  NinchDllist_EveryoneGamers
	AloneWithFriends11                NinchDllist_AloneWithFriends
	EveryoneGamers12                  NinchDllist_EveryoneGamers
	AloneWithFriends12                NinchDllist_AloneWithFriends
	Unknown15                         uint64
	EveryoneGamersAllAgesAndGenders   NinchDllist_EveryoneGamers
	AloneWithFriendsAllAgesAndGenders NinchDllist_AloneWithFriends
	Unknown16                         []uint8
	Unknown17                         uint64
	Online                            NinchDllist_YesNo
	VideoFlag                         NinchDllist_YesNo
	Multiplayer                       NinchDllist_YesNo
	Unknown18                         []uint8
	Unknown19                         uint64
	Medal                             NinchDllist_Medal
	Unknown20                         []uint8
	Title string
	Subtitle string
	ShortTitle string
	_io                               *kaitai.Stream
	_root                             *NinchDllist
	_parent                           interface{}
	_f_companyEntry                   bool
	companyEntry                      *NinchDllist_CompanyTable
}
func NewNinchDllist_TitleTable() *NinchDllist_TitleTable {
	return &NinchDllist_TitleTable{
	}
}

func (this *NinchDllist_TitleTable) Read(io *kaitai.Stream, parent interface{}, root *NinchDllist) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp116, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Id = uint32(tmp116)
	tmp117, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp117 = tmp117
	this.TitleId = string(tmp117)
	tmp118, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.TitleType = NinchDllist_Platforms(tmp118)
	for i := 0; i < int(3); i++ {
		_ = i
		tmp119, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Genre = append(this.Genre, NinchDllist_Genre(tmp119))
	}
	tmp120, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.CompanyOffset = uint32(tmp120)
	tmp121, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.ReleaseDateYear = uint16(tmp121)
	tmp122, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.ReleaseDateMonth = tmp122
	tmp123, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.ReleaseDateDay = tmp123
	tmp124, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.RatingId = tmp124
	for i := 0; i < int(2); i++ {
		_ = i
		tmp125, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Unknown1 = append(this.Unknown1, tmp125)
	}
	tmp126, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.Unknown2 = tmp126 != 0
	tmp127, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.CasualHardcore1 = NinchDllist_CasualHardcore(tmp127)
	tmp128, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.Unknown3 = tmp128 != 0
	tmp129, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.CasualHardcore2 = NinchDllist_CasualHardcore(tmp129)
	tmp130, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.Unknown4 = tmp130 != 0
	tmp131, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.CasualHardcore3 = NinchDllist_CasualHardcore(tmp131)
	tmp132, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.Unknown5 = tmp132 != 0
	tmp133, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.CasualHardcore4 = NinchDllist_CasualHardcore(tmp133)
	tmp134, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.Unknown6 = tmp134 != 0
	tmp135, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.CasualHardcore5 = NinchDllist_CasualHardcore(tmp135)
	tmp136, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.Unknown7 = tmp136 != 0
	tmp137, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.CasualHardcore6 = NinchDllist_CasualHardcore(tmp137)
	tmp138, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.Unknown8 = tmp138 != 0
	tmp139, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.CasualHardcore7 = NinchDllist_CasualHardcore(tmp139)
	tmp140, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.Unknown9 = tmp140 != 0
	tmp141, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.CasualHardcore8 = NinchDllist_CasualHardcore(tmp141)
	tmp142, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.Unknown10 = tmp142 != 0
	tmp143, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.CasualHardcore9 = NinchDllist_CasualHardcore(tmp143)
	tmp144, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.Unknown11 = tmp144 != 0
	tmp145, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.CasualHardcore10 = NinchDllist_CasualHardcore(tmp145)
	tmp146, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.Unknown12 = tmp146 != 0
	tmp147, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.CasualHardcore11 = NinchDllist_CasualHardcore(tmp147)
	tmp148, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.Unknown13 = tmp148 != 0
	tmp149, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.CasualHardcore12 = NinchDllist_CasualHardcore(tmp149)
	tmp150, err := this._io.ReadBitsIntBe(7)
	if err != nil {
		return err
	}
	this.Unknown14 = tmp150
	tmp151, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.CasualHardcoreAllAgesAndGenders = NinchDllist_CasualHardcore(tmp151)
	tmp152, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.EveryoneGamers1 = NinchDllist_EveryoneGamers(tmp152)
	tmp153, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.AloneWithFriends1 = NinchDllist_AloneWithFriends(tmp153)
	tmp154, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.EveryoneGamers2 = NinchDllist_EveryoneGamers(tmp154)
	tmp155, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.AloneWithFriends2 = NinchDllist_AloneWithFriends(tmp155)
	tmp156, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.EveryoneGamers3 = NinchDllist_EveryoneGamers(tmp156)
	tmp157, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.AloneWithFriends3 = NinchDllist_AloneWithFriends(tmp157)
	tmp158, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.EveryoneGamers4 = NinchDllist_EveryoneGamers(tmp158)
	tmp159, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.AloneWithFriends4 = NinchDllist_AloneWithFriends(tmp159)
	tmp160, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.EveryoneGamers5 = NinchDllist_EveryoneGamers(tmp160)
	tmp161, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.AloneWithFriends5 = NinchDllist_AloneWithFriends(tmp161)
	tmp162, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.EveryoneGamers6 = NinchDllist_EveryoneGamers(tmp162)
	tmp163, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.AloneWithFriends6 = NinchDllist_AloneWithFriends(tmp163)
	tmp164, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.EveryoneGamers7 = NinchDllist_EveryoneGamers(tmp164)
	tmp165, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.AloneWithFriends7 = NinchDllist_AloneWithFriends(tmp165)
	tmp166, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.EveryoneGamers8 = NinchDllist_EveryoneGamers(tmp166)
	tmp167, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.AloneWithFriends8 = NinchDllist_AloneWithFriends(tmp167)
	tmp168, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.EveryoneGamers9 = NinchDllist_EveryoneGamers(tmp168)
	tmp169, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.AloneWithFriends9 = NinchDllist_AloneWithFriends(tmp169)
	tmp170, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.EveryoneGamers10 = NinchDllist_EveryoneGamers(tmp170)
	tmp171, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.AloneWithFriends10 = NinchDllist_AloneWithFriends(tmp171)
	tmp172, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.EveryoneGamers11 = NinchDllist_EveryoneGamers(tmp172)
	tmp173, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.AloneWithFriends11 = NinchDllist_AloneWithFriends(tmp173)
	tmp174, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.EveryoneGamers12 = NinchDllist_EveryoneGamers(tmp174)
	tmp175, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.AloneWithFriends12 = NinchDllist_AloneWithFriends(tmp175)
	tmp176, err := this._io.ReadBitsIntBe(6)
	if err != nil {
		return err
	}
	this.Unknown15 = tmp176
	tmp177, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.EveryoneGamersAllAgesAndGenders = NinchDllist_EveryoneGamers(tmp177)
	tmp178, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.AloneWithFriendsAllAgesAndGenders = NinchDllist_AloneWithFriends(tmp178)
	this._io.AlignToByte()
	for i := 0; i < int(7); i++ {
		_ = i
		tmp179, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Unknown16 = append(this.Unknown16, tmp179)
	}
	tmp180, err := this._io.ReadBitsIntBe(5)
	if err != nil {
		return err
	}
	this.Unknown17 = tmp180
	tmp181, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.Online = NinchDllist_YesNo(tmp181)
	tmp182, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.VideoFlag = NinchDllist_YesNo(tmp182)
	tmp183, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.Multiplayer = NinchDllist_YesNo(tmp183)
	this._io.AlignToByte()
	for i := 0; i < int(8); i++ {
		_ = i
		tmp184, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Unknown18 = append(this.Unknown18, tmp184)
	}
	tmp185, err := this._io.ReadBitsIntBe(5)
	if err != nil {
		return err
	}
	this.Unknown19 = tmp185
	tmp186, err := this._io.ReadBitsIntBe(3)
	if err != nil {
		return err
	}
	this.Medal = NinchDllist_Medal(tmp186)
	this._io.AlignToByte()
	for i := 0; i < int(2); i++ {
		_ = i
		tmp187, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Unknown20 = append(this.Unknown20, tmp187)
	}
	tmp188, err := this._io.ReadBytes(int(62))
	if err != nil {
		return err
	}
	tmp188 = tmp188
	tmp189, err := kaitai.BytesToStr(tmp188, unicode.UTF16(unicode.BigEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.Title = tmp189
	tmp190, err := this._io.ReadBytes(int(62))
	if err != nil {
		return err
	}
	tmp190 = tmp190
	tmp191, err := kaitai.BytesToStr(tmp190, unicode.UTF16(unicode.BigEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.Subtitle = tmp191
	tmp192, err := this._io.ReadBytes(int(62))
	if err != nil {
		return err
	}
	tmp192 = tmp192
	tmp193, err := kaitai.BytesToStr(tmp192, unicode.UTF16(unicode.BigEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.ShortTitle = tmp193
	return err
}
func (this *NinchDllist_TitleTable) CompanyEntry() (v *NinchDllist_CompanyTable, err error) {
	if (this._f_companyEntry) {
		return this.companyEntry, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.CompanyOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp194 := NewNinchDllist_CompanyTable()
	err = tmp194.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.companyEntry = tmp194
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_companyEntry = true
	this._f_companyEntry = true
	return this.companyEntry, nil
}

/**
 * Null when there's no release date.
 */

/**
 * Null when there's no release date.
 */

/**
 * Null when there's no release date.
 */
type NinchDllist_DemosTable struct {
	Id uint32
	Title string
	Subtitle string
	Titleid uint32
	CompanyOffset uint32
	RemovalYear uint16
	RemovalMonth uint8
	RemovalDay uint8
	Unknown uint32
	RatingId uint8
	NewTag uint8
	NewTagIndex uint8
	Unknown2 []uint8
	_io *kaitai.Stream
	_root *NinchDllist
	_parent *NinchDllist
	_f_companyEntry bool
	companyEntry *NinchDllist_CompanyTable
}
func NewNinchDllist_DemosTable() *NinchDllist_DemosTable {
	return &NinchDllist_DemosTable{
	}
}

func (this *NinchDllist_DemosTable) Read(io *kaitai.Stream, parent *NinchDllist, root *NinchDllist) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp195, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Id = uint32(tmp195)
	tmp196, err := this._io.ReadBytes(int(62))
	if err != nil {
		return err
	}
	tmp196 = tmp196
	tmp197, err := kaitai.BytesToStr(tmp196, unicode.UTF16(unicode.BigEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.Title = tmp197
	tmp198, err := this._io.ReadBytes(int(62))
	if err != nil {
		return err
	}
	tmp198 = tmp198
	tmp199, err := kaitai.BytesToStr(tmp198, unicode.UTF16(unicode.BigEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.Subtitle = tmp199
	tmp200, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Titleid = uint32(tmp200)
	tmp201, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.CompanyOffset = uint32(tmp201)
	tmp202, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.RemovalYear = uint16(tmp202)
	tmp203, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.RemovalMonth = tmp203
	tmp204, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.RemovalDay = tmp204
	tmp205, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Unknown = uint32(tmp205)
	tmp206, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.RatingId = tmp206
	tmp207, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NewTag = tmp207
	tmp208, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NewTagIndex = tmp208
	for i := 0; i < int(205); i++ {
		_ = i
		tmp209, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Unknown2 = append(this.Unknown2, tmp209)
	}
	return err
}
func (this *NinchDllist_DemosTable) CompanyEntry() (v *NinchDllist_CompanyTable, err error) {
	if (this._f_companyEntry) {
		return this.companyEntry, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.CompanyOffset), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp210 := NewNinchDllist_CompanyTable()
	err = tmp210.Read(this._io, this, this._root)
	if err != nil {
		return nil, err
	}
	this.companyEntry = tmp210
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_companyEntry = true
	this._f_companyEntry = true
	return this.companyEntry, nil
}

/**
 * Optional.
 */

/**
 * Null when there's no end of distribution date.
 */

/**
 * Null when there's no end of distribution date.
 */

/**
 * Null when there's no end of distribution date.
 */

/**
 * When not zero, seems to display the "NEW" tag.
 */

/**
 * Might be the index for the order of demos with the "NEW" tag.
 */
